[build]
  publish = "public"
  functions = "netlify/functions"
  command = ""

[functions]
  node_bundler = "esbuild"

[[headers]]
  for = "/assets/img/*"
  [headers.values]
    Cache-Control = "public, max-age=86400"

[[headers]]
  for = "/assets/fonts/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/feltoltes/*"
  [headers.values]
    X-Robots-Tag = "noindex"
